export const EXERCISE_CREATE_EXERCISE = 'EXERCISE_CREATE_EXERCISE';
export const EXERCISE_UPDATE_EXERCISE = 'EXERCISE_UPDATE_EXERCISE';
export const EXERCISE_DELETE_EXERCISE = 'EXERCISE_DELETE_EXERCISE';
export const EXERCISE_SET_ALL_EXERCISES = 'EXERCISE_SET_ALL_EXERCISES';

export const EXERCISE_SET_ERROR = 'EXERCISE_SET_ERROR';
export const EXERCISE_SET_LOADING_TRUE = 'EXERCISE_SET_LOADING_TRUE';

export const EXERCISE_SET_CREATE_ACTION = 'EXERCISE_SET_CREATE_ACTION';
export const EXERCISE_SET_UPDATE_ACTION = 'EXERCISE_SET_UPDATE_ACTION';
export const EXERCISE_SET_DELETE_ACTION = 'EXERCISE_SET_DELETE_ACTION';
export const EXERCISE_UNSET_ACTION = 'EXERCISE_UNSET_ACTION';
export const EXERCISE_LOGIN = 'EXERCISE_LOGIN';
export const SET_EXERCISE_CREDENTIALS = 'SET_EXERCISE_CREDENTIALS';
export const LOGOUT = 'LOGOUT';
