export const USER_CREATE_EXERCISEROUTINE = 'USER_CREATE_EXERCISEROUTINE';
export const USER_UPDATE_EXERCISEROUTINE = 'USER_UPDATE_EXERCISEROUTINE';
export const USER_DELETE_EXERCISEROUTINE = 'USER_DELETE_EXERCISEROUTINE';
export const USER_SET_ALL_EXERCISEROUTINES = 'USER_SET_ALL_EXERCISEROUTINES';

export const EXERCISEROUTINE_SET_ERROR = 'EXERCISEROUTINE_SET_ERROR';
export const EXERCISEROUTINE_SET_LOADING_TRUE = 'EXERCISEROUTINE_SET_LOADING_TRUE';

export const EXERCISEROUTINE_SET_CREATE_ACTION = 'EXERCISEROUTINE_SET_CREATE_ACTION';
export const EXERCISEROUTINE_SET_UPDATE_ACTION = 'EXERCISEROUTINE_SET_UPDATE_ACTION';
export const EXERCISEROUTINE_SET_DELETE_ACTION = 'EXERCISEROUTINE_SET_DELETE_ACTION';
export const EXERCISEROUTINE_SET_COPYROUTINE_ACTION = 'EXERCISEROUTINE_SET_COPYROUTINE_ACTION';
export const EXERCISEROUTINE_SET_DELETEALLROUTINE_ACTION = 'EXERCISEROUTINE_SET_DELETEALLROUTINE_ACTION';


export const EXERCISEROUTINE_UNSET_ACTION = 'EXERCISEROUTINE_UNSET_ACTION';

