export const USER_CREATE_EXERCISE = 'USER_CREATE_EXERCISE';
export const USER_UPDATE_EXERCISE = 'USER_UPDATE_EXERCISE';
export const USER_DELETE_EXERCISE = 'USER_DELETE_EXERCISE';
export const USER_SET_ALL_EXERCISES = 'USER_SET_ALL_EXERCISES';

export const EXERCISE_SET_ERROR = 'EXERCISE_SET_ERROR';
export const EXERCISE_SET_LOADING_TRUE = 'EXERCISE_SET_LOADING_TRUE';

export const EXERCISE_SET_CREATE_ACTION = 'EXERCISE_SET_CREATE_ACTION';
export const EXERCISE_SET_UPDATE_ACTION = 'EXERCISE_SET_UPDATE_ACTION';
export const EXERCISE_SET_DELETE_ACTION = 'EXERCISE_SET_DELETE_ACTION';
export const EXERCISE_UNSET_ACTION = 'EXERCISE_UNSET_ACTION';

