export const USER_CREATE_HEALTH = 'USER_CREATE_HEALTH';
export const USER_UPDATE_HEALTH = 'USER_UPDATE_HEALTH';
export const USER_DELETE_HEALTH = 'USER_DELETE_HEALTH';
export const USER_SET_ALL_HEALTHS = 'USER_SET_ALL_HEALTHS';

export const HEALTH_SET_ERROR = 'HEALTH_SET_ERROR';
export const HEALTH_SET_LOADING_TRUE = 'HEALTH_SET_LOADING_TRUE';

export const HEALTH_SET_CREATE_ACTION = 'HEALTH_SET_CREATE_ACTION';
export const HEALTH_SET_UPDATE_ACTION = 'HEALTH_SET_UPDATE_ACTION';
export const HEALTH_SET_DELETE_ACTION = 'HEALTH_SET_DELETE_ACTION';
export const HEALTH_SET_CONSULT_ACTION = 'HEALTH_SET_CONSULT_ACTION';
export const HEALTH_UNSET_ACTION = 'HEALTH_UNSET_ACTION';