export const USER_CREATE_PERMISSION = 'USER_CREATE_PERMISSION';
export const USER_UPDATE_PERMISSION = 'USER_UPDATE_PERMISSION';
export const USER_DELETE_PERMISSION = 'USER_DELETE_PERMISSION';
export const USER_SET_ALL_PERMISSIONS = 'USER_SET_ALL_PERMISSIONS';
export const USER_SET_USER_PERMISSIONS = 'USER_SET_USER_PERMISSIONS';

export const PERMISSION_SET_ERROR = 'PERMISSION_SET_ERROR';
export const PERMISSION_SET_LOADING_TRUE = 'PERMISSION_SET_LOADING_TRUE';

export const PERMISSION_SET_CREATE_ACTION = 'PERMISSION_SET_CREATE_ACTION';
export const PERMISSION_SET_UPDATE_ACTION = 'PERMISSION_SET_UPDATE_ACTION';
export const PERMISSION_SET_DELETE_ACTION = 'PERMISSION_SET_DELETE_ACTION';
export const PERMISSION_UNSET_ACTION = 'PERMISSION_UNSET_ACTION';
