export const USER_CREATE_POST = 'USER_CREATE_POST';
export const USER_UPDATE_POST = 'USER_UPDATE_POST';
export const USER_DELETE_POST = 'USER_DELETE_POST';
export const USER_SET_ALL_POSTS = 'USER_SET_ALL_POSTS';

export const POST_SET_ERROR = 'POST_SET_ERROR';
export const POST_SET_LOADING_TRUE = 'POST_SET_LOADING_TRUE';

export const POST_SET_CREATE_ACTION = 'POST_SET_CREATE_ACTION';
export const POST_SET_UPDATE_ACTION = 'POST_SET_UPDATE_ACTION';
export const POST_SET_DELETE_ACTION = 'POST_SET_DELETE_ACTION';
export const POST_UNSET_ACTION = 'POST_UNSET_ACTION';