export const USER_CREATE_ROUTINE = 'USER_CREATE_ROUTINE';
export const USER_UPDATE_ROUTINE = 'USER_UPDATE_ROUTINE';
export const USER_DELETE_ROUTINE = 'USER_DELETE_ROUTINE';
export const USER_SET_ALL_ROUTINES = 'USER_SET_ALL_ROUTINES';

export const ROUTINE_SET_ERROR = 'ROUTINE_SET_ERROR';
export const ROUTINE_SET_LOADING_TRUE = 'ROUTINE_SET_LOADING_TRUE';

export const ROUTINE_SET_CREATE_ACTION = 'ROUTINE_SET_CREATE_ACTION';
export const ROUTINE_SET_UPDATE_ACTION = 'ROUTINE_SET_UPDATE_ACTION';
export const ROUTINE_SET_DELETE_ACTION = 'ROUTINE_SET_DELETE_ACTION';
export const ROUTINE_SET_ROUTINEEXERCISE_ACTION = 'ROUTINE_SET_ROUTINEEXERCISE_ACTION';

export const ROUTINE_UNSET_ACTION = 'ROUTINE_UNSET_ACTION';


