export const USER_CREATE_SUBSCRIPTION = 'USER_CREATE_SUBSCRIPTION';
export const USER_UPDATE_SUBSCRIPTION = 'USER_UPDATE_SUBSCRIPTION';
export const USER_DELETE_SUBSCRIPTION = 'USER_DELETE_SUBSCRIPTION';
export const USER_SET_ALL_SUBSCRIPTIONS = 'USER_SET_ALL_SUBSCRIPTIONS';

export const SUBSCRIPTION_SET_ERROR = 'SUBSCRIPTION_SET_ERROR';
export const SUBSCRIPTION_SET_LOADING_TRUE = 'SUBSCRIPTION_SET_LOADING_TRUE';

export const SUBSCRIPTION_SET_CREATE_ACTION = 'SUBSCRIPTION_SET_CREATE_ACTION';
export const SUBSCRIPTION_SET_UPDATE_ACTION = 'SUBSCRIPTION_SET_UPDATE_ACTION';
export const SUBSCRIPTION_SET_DELETE_ACTION = 'SUBSCRIPTION_SET_DELETE_ACTION';
export const SUBSCRIPTION_UNSET_ACTION = 'SUBSCRIPTION_UNSET_ACTION';