export const USER_CREATE_USER = 'USER_CREATE_USER';
export const USER_UPDATE_USER = 'USER_UPDATE_USER';
export const USER_DELETE_USER = 'USER_DELETE_USER';
export const USER_SET_ALL_USERS = 'USER_SET_ALL_USERS';

export const USER_SET_ERROR = 'USER_SET_ERROR';
export const USER_SET_LOADING_TRUE = 'USER_SET_LOADING_TRUE';

export const USER_SET_CREATE_ACTION = 'USER_SET_CREATE_ACTION';
export const USER_SET_UPDATE_ACTION = 'USER_SET_UPDATE_ACTION';
export const USER_SET_DELETE_ACTION = 'USER_SET_DELETE_ACTION';
export const USER_UNSET_ACTION = 'USER_UNSET_ACTION';
export const USER_LOGIN = 'USER_LOGIN'
export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS'
export const LOGOUT = 'LOGOUT'
