export const USER_CREATE_VALORATION = 'USER_CREATE_VALORATION';
export const USER_UPDATE_VALORATION = 'USER_UPDATE_VALORATION';
export const USER_DELETE_VALORATION = 'USER_DELETE_VALORATION';
export const USER_SET_ALL_VALORATIONS = 'USER_SET_ALL_VALORATIONS';

export const VALORATION_SET_ERROR = 'VALORATION_SET_ERROR';
export const VALORATION_SET_LOADING_TRUE = 'VALORATION_SET_LOADING_TRUE';
export const VALORATION_UNSET_ACTION = 'VALORATION_UNSET_ACTION';