export const USER_CREATE_WORKOUTEVENT = 'USER_CREATE_WORKOUTEVENT';
export const USER_UPDATE_WORKOUTEVENT = 'USER_UPDATE_WORKOUTEVENT';
export const USER_DELETE_WORKOUTEVENT = 'USER_DELETE_WORKOUTEVENT';
export const USER_SET_ALL_WORKOUTEVENTS = 'USER_SET_ALL_WORKOUTEVENTS';

export const WORKOUTEVENT_SET_ERROR = 'WORKOUTEVENT_SET_ERROR';
export const WORKOUTEVENT_SET_LOADING_TRUE = 'WORKOUTEVENT_SET_LOADING_TRUE';

export const WORKOUTEVENT_SET_CREATE_ACTION = 'WORKOUTEVENT_SET_CREATE_ACTION';
export const WORKOUTEVENT_SET_UPDATE_ACTION = 'WORKOUTEVENT_SET_UPDATE_ACTION';
export const WORKOUTEVENT_SET_DELETE_ACTION = 'WORKOUTEVENT_SET_DELETE_ACTION';
export const WORKOUTEVENT_SET_LISTPARTICIPANTS_ACTION = 'WORKOUTEVENT_SET_LISTPARTICIPANTS_ACTION';
export const WORKOUTEVENT_UNSET_ACTION = 'WORKOUTEVENT_UNSET_ACTION';