export const WORKOUTEVENT_CREATE_WORKOUTEVENT =
  'WORKOUTEVENT_CREATE_WORKOUTEVENT';
export const WORKOUTEVENT_UPDATE_WORKOUTEVENT =
  'WORKOUTEVENT_UPDATE_WORKOUTEVENT';
export const WORKOUTEVENT_DELETE_WORKOUTEVENT =
  'WORKOUTEVENT_DELETE_WORKOUTEVENT';
export const WORKOUTEVENT_SET_ALL_WORKOUTEVENTS =
  'WORKOUTEVENT_SET_ALL_WORKOUTEVENTS';

export const WORKOUTEVENT_SET_ERROR = 'WORKOUTEVENT_SET_ERROR';
export const WORKOUTEVENT_SET_LOADING_TRUE = 'WORKOUTEVENT_SET_LOADING_TRUE';

export const WORKOUTEVENT_SET_CREATE_ACTION = 'WORKOUTEVENT_SET_CREATE_ACTION';
export const WORKOUTEVENT_SET_UPDATE_ACTION = 'WORKOUTEVENT_SET_UPDATE_ACTION';
export const WORKOUTEVENT_SET_DELETE_ACTION = 'WORKOUTEVENT_SET_DELETE_ACTION';
export const WORKOUTEVENT_UNSET_ACTION = 'WORKOUTEVENT_UNSET_ACTION';
export const WORKOUTEVENT_LOGIN = 'WORKOUTEVENT_LOGIN';
export const SET_WORKOUTEVENT_CREDENTIALS = 'SET_WORKOUTEVENT_CREDENTIALS';
export const LOGOUT = 'LOGOUT';
